# frpc.toml
serverAddr = "foo.dreamshell.org"
serverPort = 7000
auth.method = "oidc"
auth.oidc.audience = "https://github.com/G-Structure"  # Adjust to your repo or org
auth.oidc.scope = "openid profile email"
# In GitHub Actions, obtain OIDC token and set auth.oidc.token

[[proxies]]
name = "webserver"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8000
remotePort = 8080
