# frpc.toml
serverAddr = "foo.flakery.xyz"
serverPort = 7000

[[proxies]]
name = "webserver"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8000
remotePort = 8080


# frpc.toml
auth.method = "oidc"
auth.oidc.clientID = "frp-client"  # Replace with your actual client ID
auth.oidc.clientSecret = ""  # Replace with your actual client secret
auth.oidc.audience = "frp-client/.default"
auth.oidc.tokenEndpointURL = "https://kc.flakery.xyz/realms/frp/protocol/openid-connect/token"