name: "Terraform"

on:
  push:
    branches: [ "main", "master"]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
        
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform (${{ matrix.directory }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - oidc
          - state-management
          - reverse-proxy
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::150301572911:role/github-oidc-provider-aws
        aws-region: us-west-2

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      env:
        TF_BACKEND_BUCKET: terraform-state-1f567871bd52790f
        TF_BACKEND_LOCK_TABLE: terraform-state-lock-1f567871bd52790f

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      if: github.event_name == 'pull_request'

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve